apiVersion: v1
kind: Service
metadata:
  name: mindtrack-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
  labels:
    app: mindtrack
spec:
  type: LoadBalancer
  selector:
    app: mindtrack
  ports:
    - name: http
      port: 80
      targetPort: 3000
